onboarding = false

[keys]
prefix = "ctrl+alt+cmd+a"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "Lazygitを開く"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "90%"
height = "90%"

[experimental]
pane_history = false
